Refactor using pandas
computational-ms/unimod-mapper pull request #38
Opened 2021-11-15 21:53 UTC by fu

2021-11-16 20:46 UTC, fu commented
Before we merge this, we need to fix 10 tests in ursgal2 - help ! :)

2021-11-17 08:26 UTC, fu commented
It works now.

2021-11-19 11:48 UTC, MKoesters requested changes

2021-11-19 11:48 UTC, MKoesters commented on unimod_mapper/unimod_mapper.py
> +    def mass_to_combos(self, mass, n=2, decimals=3):
docstring would be helpful

2021-11-19 11:48 UTC, MKoesters commented on unimod_mapper/unimod_mapper.py
> +        fraction = 1 / 10 ** (decimals + 1)
What are these magic numbers?

2021-11-20 16:43 UTC, merged